DEBUG = False
SECRET_KEY = 'secret' # change to your own secret key
DATA_DIR = 'data_dir'
DRAFTS_DIR = 'data_dir/drafts'
DRAFTS_INDEX = 'data_dir/drafts/index.json'
BLOGS_DIR = 'data_dir/published'
BLOGS_INDEX = 'data_dir/published/index.json'
ROOT_FILE = 'blog_server/root_user.pickle'
ROOT_NAME = 'admin'
ROOT_PSWD = 'password123'
